In [1]:
import numpy as np
import cvxpy as cp
import cvxpy
print(cp.installed_solvers()) 

['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCS']


In [10]:
del num_companies
#repeat is dim element wise repeat: each element is assigned a number of repeating times.

In [11]:
#data setting
num_building = 10
num_company = 20

#capacity of each building
cap = np.ceil(np.random.random((num_building,1))*100)
#volumn needed by each company
v = np.random.random((num_company,1))*40
#reward matrix for each company(row) being inside each building(col)
r_mat = np.random.random((num_company,num_building))
#prob matrix for each company and building
s_mat = np.random.random((num_company,num_building))

In [27]:
G.shape,v_mat.shape

((10, 200), (200, 1))

In [43]:
#Variable to be solved which represent the relationship between company and building
eij = cp.Variable((num_company*num_building,1),boolean=True)

#condition1: Each company only has relationship with only 1 building
K = np.eye(num_company,num_company)
xpK = list(np.ones(num_company)*num_building)
K = np.repeat(K,xpK,axis=1)#sum of row
cond1 = K@eij == 1

#condition2: Each building has limited capacity
G = np.eye(num_building,num_building)
G = np.tile(G,[1,num_company])
v_mat = np.tile(v,[1,num_building]).reshape(-1,1)
cond2 = G@(cp.multiply(v_mat,eij)) <= cap

#cost function
rs = r_mat.reshape(-1,1)*s_mat.reshape(-1,1)
energy = rs.reshape(1,-1)@eij

portfolio_problem = cp.Problem(cp.Maximize(energy), [cond1,cond2])

portfolio_problem.solve(solve=cp.GLPK_MI)

opt_e = eij.value
opt_e = opt_e.reshape((num_company,num_building))
#check cond1
print('How many buildings are assigned to the company:')
print(np.sum(opt_e,axis=1))

#look building info
print('How many companies are assigned into the building:')
print(np.sum(opt_e,axis=0))

How many buildings are assigned to the company:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
How many companies are assigned into the building:
[3. 3. 3. 0. 2. 4. 0. 3. 2. 0.]


In [47]:
#end 
print(portfolio_problem.solution.opt_val)

[11.85181571]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

array([3., 3., 3., 0., 2., 4., 0., 3., 2., 0.])

In [38]:
print(eij.value),print(portfolio_problem.status)

[[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.

(None, None)